package smartfactoryV2;

import com.alee.laf.WebLookAndFeel;
import com.jidesoft.plaf.LookAndFeelFactory;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import login.Identification;
import org.jdesktop.swingx.painter.ImagePainter;

/**
 *
 * @author Victor Kadiata
 */
public class SplashScreen extends javax.swing.JFrame {

    public static Identification getIdentification() {
        return identification;
    }

    public SplashScreen() {
//        final String workingDir = System.getProperty("user.dir");
        initComponents();
        try {
            this.setIconImage(new ImageIcon(cl.getResource("images/iDeaX.jpg")).getImage());
            panelImage.setBackgroundPainter(new ImagePainter(
                    ImageIO.read(cl.getResource("images/Smart_Factory Logo300x134_2.jpg"))));
        } catch (IOException | NullPointerException | IllegalArgumentException ex) {
        }
        time = new Timer(150, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                prbSplashScreen.setValue(motion);
                if (motion == 10) {
                    lblSplash.setText("Starting ...");
                } else if (motion == 45) {
                    lblSplash.setText("Loading smarfactory modules ...");
                } else if (motion == 60) {
                    try {
                        lblSplash.setText("Initialization ...");
                        Thread.sleep(2000);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                    lblSplash.setText("Executing queries ...");
//                System.out.println(workingDir + File.separator + "src\\sqldump\\smartNewDump.sql");
//                System.out.println(getClass().getResourceAsStream("/sqldump/smartNewDump.sql").toString());
                    //Run the restore database in a thread
//                    new RestoreDatabase("root", "wnnr123", workingDir + File.separator + "src\\sqldump\\smartNewDump.sql").start();
//                new RestoreDatabase("root", "wnnr123",
//                        getClass().getResourceAsStream("./sqldump/smartNewDump.sql")).start();
//                    lblSplash.setText("Launching application ...");
                }
                if (motion == 100) {
                    motion = 0;
                    time.stop();
                    dispose();
                    System.gc();
                    WebLookAndFeel.install();
                    LookAndFeelFactory.installJideExtension(LookAndFeelFactory.XERTO_STYLE);
//                    LookAndFeelFactory.installDefaultLookAndFeelAndExtension();
                    identification = new Identification(null, false);
                    identification.setVisible(true);
                }
                motion++;
            }
        });
        time.start();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage = new org.jdesktop.swingx.JXPanel();
        lblSplash = new javax.swing.JLabel();
        prbSplashScreen = new javax.swing.JProgressBar();
        btnExit = new com.jidesoft.swing.JideButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Starting SmartFactory Report Tool");
        setUndecorated(true);
        setResizable(false);

        panelImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));

        lblSplash.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        lblSplash.setForeground(new java.awt.Color(0, 0, 102));
        lblSplash.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        prbSplashScreen.setForeground(new java.awt.Color(0, 0, 102));
        prbSplashScreen.setString("");
        prbSplashScreen.setStringPainted(true);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/office/remove_package_rollover.png"))); // NOI18N
        btnExit.setToolTipText("Exit application");
        btnExit.setFocusable(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImageLayout = new javax.swing.GroupLayout(panelImage);
        panelImage.setLayout(panelImageLayout);
        panelImageLayout.setHorizontalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelImageLayout.createSequentialGroup()
                .addGroup(panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prbSplashScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelImageLayout.setVerticalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImageLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lblSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(prbSplashScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        prbSplashScreen.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
//        new Thread(new Runnable() {
//
//            @Override
//            public void run() {
//                new WritePropertiesFile("close", ConnectDB.serverIP, "5m");
//            }
//        }).start();
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jidesoft.swing.JideButton btnExit;
    public static javax.swing.JLabel lblSplash;
    private org.jdesktop.swingx.JXPanel panelImage;
    private javax.swing.JProgressBar prbSplashScreen;
    // End of variables declaration//GEN-END:variables
    private byte motion = 1;
    private Timer time = null;
    private static Identification identification;
    private ClassLoader cl = this.getClass().getClassLoader();
}
