package smartfactoryV2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.Timer;
import javax.swing.ToolTipManager;
import login.Identification;
import org.jdesktop.swingx.painter.ImagePainter;
import resources.WritePropertiesFile;

/**
 *
 * @author Victor Kadiata
 */
public class SplashScreen extends javax.swing.JFrame {

    public SplashScreen() {
        this.parent = (JFrame) this;
        final String workingDir = System.getProperty("user.dir");
        initComponents();
        ToolTipManager.sharedInstance().setDismissDelay(20000);
        ToolTipManager.sharedInstance().setInitialDelay(100);
        this.setIconImage(new ImageIcon(getClass().getResource("/images/iDeaX.jpg")).getImage());
        time = new Timer(150, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                prbSplashScreen.setValue(motion);
                if (motion == 15) {
                    try {
                        lblSplash.setText("Starting ...");
                        Thread.sleep(400);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                } else if (motion == 50) {
                    try {
                        lblSplash.setText("Charging of smarfactory modules ...");
                        Thread.sleep(900);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                } else if (motion == 75) {
                    try {
                        lblSplash.setText("Initialization ...");
                        Thread.sleep(5000);
                        lblSplash.setText("Executing queries ...");
                        Thread.sleep(2000);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
//                System.out.println(workingDir + File.separator + "src\\sqldump\\smartNewDump.sql");
//                System.out.println(getClass().getResourceAsStream("/sqldump/smartNewDump.sql").toString());
                    //Run the restore database in a thread
//                    new RestoreDatabase("root", "wnnr123", workingDir + File.separator + "src\\sqldump\\smartNewDump.sql").start();
//                new RestoreDatabase("root", "wnnr123",
//                        getClass().getResourceAsStream("./sqldump/smartNewDump.sql")).start();
//                    lblSplash.setText("Launching application ...");
                }
                if (motion == 110) {
                    dispose();
                    time.stop();
//                    createUserTableInDatabase();//create the user table in the database
                    identification = new Identification(null, true);
                    identification.setVisible(true);
                }
                motion++;
            }
        });
        setLocationRelativeTo(null);
        time.start();
        try {
            jXPanel1.setBackgroundPainter(new ImagePainter(
                    ImageIO.read(getClass().getResource(("/images/Smart_Factory Logo300x134_2.jpg")))));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        lblSplash = new javax.swing.JLabel();
        prbSplashScreen = new javax.swing.JProgressBar();
        btnExit = new com.jidesoft.swing.JideButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Starting SmartFactory Report Tool");
        setUndecorated(true);
        setResizable(false);

        jXPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));

        lblSplash.setFont(new java.awt.Font("Viner Hand ITC", 0, 11)); // NOI18N
        lblSplash.setForeground(new java.awt.Color(0, 0, 102));
        lblSplash.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        prbSplashScreen.setForeground(new java.awt.Color(0, 0, 102));
        prbSplashScreen.setString("");
        prbSplashScreen.setStringPainted(true);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/office/remove_package_rollover.png"))); // NOI18N
        btnExit.setToolTipText("Exit application");
        btnExit.setFocusable(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prbSplashScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel1Layout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lblSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(prbSplashScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        prbSplashScreen.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
//        new Thread(new Runnable() {
//
//            @Override
//            public void run() {
//                new WritePropertiesFile("close", ConnectDB.serverIP, "5m");
//            }
//        }).start();
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jidesoft.swing.JideButton btnExit;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    public static javax.swing.JLabel lblSplash;
    private javax.swing.JProgressBar prbSplashScreen;
    // End of variables declaration//GEN-END:variables
    int motion = 1;
    Timer time;
    JFrame parent;
    public static Identification identification;
}
