package reportSettings;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.prefs.Preferences;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author Victor Kadiata
 */
public class ReportOptions extends javax.swing.JDialog {

    public boolean isWindowClosed() {
        return windowClosed;
    }

    public Image getPhoto() {
        return photo;
    }

    public void setPhoto(Image photo) {
        this.photo = photo;
    }

    public boolean isAddTable() {
        return addTable;
    }

    public void setAddTable(boolean addTable) {
        this.addTable = addTable;
    }

    public boolean isAddChart() {
        return addChart;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public void setAddChart(boolean addChart) {
        this.addChart = addChart;
    }

    public String getCompanyTitle() {
        return companyTitle;
    }

    public void setCompanyTitle(String companyTitle) {
        this.companyTitle = companyTitle;
    }

    public String getReportTitle() {
        return reportTitle;
    }

    public void setReportTitle(String reportTitle) {
        this.reportTitle = reportTitle;
    }

    public ReportOptions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        attribs = new SimpleAttributeSet();
        StyleConstants.setAlignment(attribs, StyleConstants.ALIGN_CENTER);
        jPanel1.requestFocus();
        Timer time = new Timer(100, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                if ((chkPrintChart.isSelected() || chkPrintTable.isSelected())
                        && !txtCompanyTitle.getText().isEmpty()
                        && !txtCompanyTitle.getText().equalsIgnoreCase("---   Company Trademark Identification   ---")
                        && !txtReportTitle.getText().isEmpty()
                        && !txtReportTitle.getText().equalsIgnoreCase("---   Main title of the report   ---")) {
                    btnPrintReport.setEnabled(true);
                } else {
                    btnPrintReport.setEnabled(false);
                }
            }
        });
        time.start();
        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                windowClosed = false;
            }
        });
        txtAddress.addKeyListener(new KeyAdapter() {

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_TAB) {
                    if (e.getModifiers() > 0) {
                        txtAddress.transferFocusBackward();
                    } else {
                        txtAddress.transferFocus();
                    }
                    e.consume();
                }
            }
        });
        if (this.companyTitle != null) {
            txtCompanyTitle.setText(this.companyTitle);
        }
        loadComponents();
        txtLogo.setFileFilter(new FileNameExtensionFilter("Images", "jpg", "gif", "bmp", "png"));
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        chkPrintTable = new javax.swing.JCheckBox();
        chkPrintChart = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnPrintReport = new com.jidesoft.swing.JideButton();
        jLabel2 = new javax.swing.JLabel();
        txtCompanyTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtReportTitle = new javax.swing.JTextField();
        txtLogo = new com.jidesoft.combobox.FileChooserExComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jXTitledSeparator1 = new org.jdesktop.swingx.JXTitledSeparator();
        txtEmail = new org.jdesktop.swingx.JXTextField();
        txtWebSite = new org.jdesktop.swingx.JXTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Report Options");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html>Options<font color=red>*</font></html>", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10), new java.awt.Color(0, 0, 255))); // NOI18N

        chkPrintTable.setBackground(new java.awt.Color(255, 255, 255));
        chkPrintTable.setSelected(true);
        chkPrintTable.setText("Print Table");
        chkPrintTable.setFocusable(false);

        chkPrintChart.setBackground(new java.awt.Color(255, 255, 255));
        chkPrintChart.setText("Print Chart");
        chkPrintChart.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkPrintTable)
                    .addComponent(chkPrintChart))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkPrintTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPrintChart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Choose Logo:");

        btnPrintReport.setButtonStyle(com.jidesoft.swing.JideButton.TOOLBOX_STYLE);
        btnPrintReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/fileprint(21).png"))); // NOI18N
        btnPrintReport.setText("Print Report");
        btnPrintReport.setFocusable(false);
        btnPrintReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReportActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("<html>Company Title<font color=red>*</font></html>");

        txtCompanyTitle.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        txtCompanyTitle.setForeground(new java.awt.Color(153, 153, 153));
        txtCompanyTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCompanyTitle.setText("---   Company Trademark Identification   ---");
        txtCompanyTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCompanyTitleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCompanyTitleFocusLost(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("<html>Report Title<font color=red>*</font></html>");

        txtReportTitle.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        txtReportTitle.setForeground(new java.awt.Color(153, 153, 153));
        txtReportTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReportTitle.setText("---   Main title of the report   ---");
        txtReportTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtReportTitleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReportTitleFocusLost(evt);
            }
        });

        txtLogo.setFocusable(false);
        txtLogo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtLogoItemStateChanged(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Contact Email:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Website:");

        jXTitledSeparator1.setForeground(new java.awt.Color(0, 0, 204));
        jXTitledSeparator1.setTitle("Location address");

        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setText("---   Company contact email   ---");
        txtEmail.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        txtWebSite.setForeground(new java.awt.Color(153, 153, 153));
        txtWebSite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtWebSite.setText("---   Company website   ---");
        txtWebSite.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        txtWebSite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtWebSiteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWebSiteFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel11.setText("<html><font color=red>*</font>Required field</html>");

        txtAddress.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(153, 153, 153));
        txtAddress.setText("---   Company physical address   ---");
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddressFocusLost(evt);
            }
        });
        jScrollPane4.setViewportView(txtAddress);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCompanyTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(txtReportTitle)
                            .addComponent(txtLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtWebSite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jXTitledSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrintReport, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCompanyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReportTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(txtWebSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXTitledSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnPrintReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReportActionPerformed
        if (chkPrintChart.isSelected()) {
            setAddChart(true);
        } else {
            setAddChart(false);
        }
        if (chkPrintTable.isSelected()) {
            setAddTable(true);
        } else {
            setAddTable(false);
        }
        setCompanyTitle(txtCompanyTitle.getText());
        prefs.put("company", getCompanyTitle());
        setReportTitle(txtReportTitle.getText());
        if (!txtEmail.getText().equalsIgnoreCase("---   Company contact email   ---")
                && !txtEmail.getText().isEmpty()) {
            setEmail(txtEmail.getText());
            prefs.put("email", getEmail());
        } else {
            setEmail("");
        }
        if (!txtWebSite.getText().equalsIgnoreCase("---   Company website   ---")
                && !txtWebSite.getText().isEmpty()) {
            setWebsite(txtWebSite.getText());
            prefs.put("website", getWebsite());
        } else {
            setWebsite("");
        }
        if (!txtAddress.getText().equalsIgnoreCase("---   Company physical address   ---")
                && !txtAddress.getText().isEmpty()) {
            setAddress(txtAddress.getText().trim());
            prefs.put("address", getAddress());
        }
        windowClosed = true;
        this.dispose();
    }//GEN-LAST:event_btnPrintReportActionPerformed

    private void txtCompanyTitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCompanyTitleFocusGained
        cursorIn(txtCompanyTitle, "---   Company Trademark Identification   ---");
        txtCompanyTitle.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_txtCompanyTitleFocusGained

    private void txtCompanyTitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCompanyTitleFocusLost
        cursorOut(txtCompanyTitle, "---   Company Trademark Identification   ---");
    }//GEN-LAST:event_txtCompanyTitleFocusLost

    private void txtReportTitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReportTitleFocusGained
        cursorIn(txtReportTitle, "---   Main title of the report   ---");
        txtReportTitle.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_txtReportTitleFocusGained

    private void txtReportTitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReportTitleFocusLost
        cursorOut(txtReportTitle, "---   Main title of the report   ---");
    }//GEN-LAST:event_txtReportTitleFocusLost

    private void txtLogoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtLogoItemStateChanged
        try {
            ImageIcon icon = new ImageIcon(txtLogo.getSelectedItem().toString());
            icon = new ImageIcon(icon.getImage().getScaledInstance(350, 250, Image.SCALE_DEFAULT));
            photo = icon.getImage();
            prefs.put("imagepath", new File(txtLogo.getSelectedItem().toString()).getAbsolutePath());
            setPhoto(photo);
//            System.out.println("b-" + txtLogo.getSelectedIndex());
        } catch (Exception ex) {
//            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtLogoItemStateChanged

    private void txtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusGained
        if (txtAddress.getText().equals("---   Company physical address   ---")) {
            txtAddress.setText("");
            txtAddress.setForeground(Color.BLACK);
            txtAddress.setFont(new java.awt.Font("Tahoma", 0, 11));
            StyleConstants.setAlignment(attribs, StyleConstants.ALIGN_LEFT);
            txtAddress.setParagraphAttributes(attribs, false);
        }
    }//GEN-LAST:event_txtAddressFocusGained

    private void txtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusLost
        if (txtAddress.getText().isEmpty()) {
            txtAddress.setText("---   Company physical address   ---");
            txtAddress.setForeground(new java.awt.Color(153, 153, 153));
            txtAddress.setFont(new java.awt.Font("Tahoma", 2, 10));
            StyleConstants.setAlignment(attribs, StyleConstants.ALIGN_LEFT);
            txtAddress.setParagraphAttributes(attribs, false);
        }
    }//GEN-LAST:event_txtAddressFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        cursorIn(txtEmail, "---   Company contact email   ---");
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        cursorOut(txtEmail, "---   Company contact email   ---");
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtWebSiteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWebSiteFocusGained
        cursorIn(txtWebSite, "---   Company website   ---");
        txtWebSite.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_txtWebSiteFocusGained

    private void txtWebSiteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWebSiteFocusLost
        cursorOut(txtWebSite, "---   Company website   ---");
    }//GEN-LAST:event_txtWebSiteFocusLost

    private void cursorIn(JTextField txtField, String text) {
        if (txtField.getText().equals(text)) {
            txtField.setForeground(Color.BLACK);
            txtField.setText("");
            txtField.setHorizontalAlignment(javax.swing.JTextField.LEADING);
        }
    }

    private void cursorOut(JTextField txtField, String text) {
        if (txtField.getText().isEmpty()) {
            txtField.setText(text);
            txtField.setForeground(new java.awt.Color(153, 153, 153));
            txtField.setFont(new java.awt.Font("Tahoma", 2, 10));
            txtField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        }
    }

    private void loadComponents() {
        txtLogo.setCurrentDirectoryPath(prefs.get("imagepath",
                FileSystemView.getFileSystemView().getRoots()[0].getAbsolutePath()));
        txtCompanyTitle.setText(prefs.get("company", "---   Company Trademark Identification   ---"));
        setTextFieldNormal(txtCompanyTitle, "---   Company Trademark Identification   ---");
        txtEmail.setText(prefs.get("email", "---   Company contact email   ---"));
        setTextFieldNormal(txtEmail, "---   Company contact email   ---");
        txtWebSite.setText(prefs.get("website", "---   Company website   ---"));
        setTextFieldNormal(txtWebSite, "---   Company website   ---");
        txtAddress.setText(prefs.get("address", "---   Company physical address   ---"));
        setTextAreaNormal(txtAddress, "---   Company physical address   ---");
    }

    private void setTextFieldNormal(JTextField txtField, String text) {
        if (!txtField.getText().equals(text)) {
            txtField.setForeground(Color.BLACK);
            txtField.setHorizontalAlignment(javax.swing.JTextField.LEADING);
            txtField.setFont(new java.awt.Font("Tahoma", 0, 11));
        }
    }

    private void setTextAreaNormal(JTextPane txtPane, String text) {
        if (!txtPane.getText().equals(text)) {
            txtPane.setForeground(Color.BLACK);
            txtPane.setFont(new java.awt.Font("Tahoma", 0, 11));
            StyleConstants.setAlignment(attribs, StyleConstants.ALIGN_LEFT);
            txtPane.setParagraphAttributes(attribs, false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jidesoft.swing.JideButton btnPrintReport;
    public javax.swing.JCheckBox chkPrintChart;
    public javax.swing.JCheckBox chkPrintTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private org.jdesktop.swingx.JXTitledSeparator jXTitledSeparator1;
    public static javax.swing.JTextPane txtAddress;
    private javax.swing.JTextField txtCompanyTitle;
    private org.jdesktop.swingx.JXTextField txtEmail;
    private com.jidesoft.combobox.FileChooserExComboBox txtLogo;
    public static javax.swing.JTextField txtReportTitle;
    private org.jdesktop.swingx.JXTextField txtWebSite;
    // End of variables declaration//GEN-END:variables
    private boolean addTable, addChart, windowClosed;
    private String companyTitle, reportTitle, email, website, address;
    private Image photo;
    private final SimpleAttributeSet attribs;
    private Preferences prefs = Preferences.userNodeForPackage(ReportOptions.class);
}
